#include "lab.h"
#define BAD_VALUE (-1.0e300)
static bool good(double x){return x>BAD_VALUE/2&&x<1.0e300;}
static double dmax(double a,double b){return a>b?a:b;}
static double dmin(double a,double b){return a<b?a:b;}
static double clamp100(double x){return x<0?0:x>100?100:x;}
static int dcmp(const void* a,const void* b){double x=*(const double*)a,y=*(const double*)b;return (x>y)-(x<y);}
static double median(double* a,size_t n){if(!n)return BAD_VALUE;qsort(a,n,sizeof(double),dcmp);return n&1?a[n/2]:(a[n/2-1]+a[n/2])/2.0;}
static double robust_mad(double* a,size_t n){if(!n)return BAD_VALUE;double tmp[64],dev[64];if(n>64)n=64;for(size_t i=0;i<n;i++)tmp[i]=a[i];double m=median(tmp,n);for(size_t i=0;i<n;i++)dev[i]=fabs(a[i]-m);return 1.4826*median(dev,n);}
static const Sample* sample_find(const Report* r,const char* suite,const char* test,int trial,int threads,size_t pattern){
    for(size_t i=0;i<r->nsamples;i++){const Sample* s=&r->samples[i];if(strcmp(s->suite,suite))continue;if(test&&strcmp(s->test,test))continue;if(trial>=0&&s->trial!=trial)continue;if(threads>=0&&s->threads!=threads)continue;if(pattern&&s->pattern_bytes!=pattern)continue;return s;}return 0;
}
static double group_median(const Report* r,const char* suite,const char* test,int threads,size_t pattern,int field){
    double v[64];size_t n=0;for(size_t i=0;i<r->nsamples&&n<64;i++){const Sample* s=&r->samples[i];if(strcmp(s->suite,suite))continue;if(test&&strcmp(s->test,test))continue;if(threads>=0&&s->threads!=threads)continue;if(pattern&&s->pattern_bytes!=pattern)continue;
        double x=field==0?s->value:field==1?s->background_gbps:field==2?s->p50:field==3?s->p99:field==4?s->p999:s->max_value;if(good(x))v[n++]=x;}return median(v,n);
}
static void linreg(const double* x,const double* y,size_t n,double* slope,double* r2){
    *slope=BAD_VALUE;*r2=BAD_VALUE;if(n<3)return;double sx=0,sy=0;for(size_t i=0;i<n;i++){sx+=x[i];sy+=y[i];}double mx=sx/n,my=sy/n,sxx=0,sxy=0,syy=0;for(size_t i=0;i<n;i++){double dx=x[i]-mx,dy=y[i]-my;sxx+=dx*dx;sxy+=dx*dy;syy+=dy*dy;}if(sxx<=0||syy<=0)return;*slope=sxy/sxx;double rr=sxy*sxy/(sxx*syy);*r2=rr<0?0:rr>1?1:rr;
}
static Diagnostic* add_diag(Report* r,const char* id,const char* title,const char* params){if(r->ndiagnostics>=MAX_DIAGNOSTICS)return 0;Diagnostic* d=&r->diagnostics[r->ndiagnostics++];memset(d,0,sizeof(*d));fmt(d->id,sizeof(d->id),"%s",id);fmt(d->title,sizeof(d->title),"%s",title);fmt(d->parameter_group,sizeof(d->parameter_group),"%s",params);fmt(d->status,sizeof(d->status),"unresolved");fmt(d->confidence,sizeof(d->confidence),"low");return d;}
static void profile_values(const Report* r,char* out,size_t cap,const char* const* keys,size_t n){
    *out=0;if(!r->profile.loaded){fmt(out,cap,"参数读取模块尚未接入；当前没有参数快照");return;}size_t used=0;for(size_t i=0;i<n;i++){const char* v=profile_get(&r->profile,keys[i]);if(!v||!*v)continue;int w=fmt(out+used,cap-used,"%s%s=%s",used?", ":"",keys[i],v);if(w<0||(size_t)w>=cap-used)break;used+=(size_t)w;}if(!used)fmt(out,cap,"profile.ini 中没有该组参数");
}
static void copy_turnaround_diag(Report* r){
    Diagnostic* d=add_diag(r,"copy_turnaround","Copy短板：读写方向切换","tRDWR / tWRRD / tWTRS / tWTRL / IMC turnaround");if(!d)return;
    const size_t g[10]={64,128,256,512,1024,2048,4096,8192,16384,65536};double effects[32],slopes[32],fits[32];size_t ne=0,ns=0;
    for(int trial=1;trial<=r->opt.repeats&&trial<=31;trial++){
        const Sample* a=sample_find(r,"copy_turnaround",0,trial,-1,g[0]);const Sample* b=sample_find(r,"copy_turnaround",0,trial,-1,g[9]);if(a&&b&&a->value>0)effects[ne++]=100.0*(b->value/a->value-1.0);
        double x[10],y[10];size_t n=0;for(int k=0;k<10;k++){const Sample* s=sample_find(r,"copy_turnaround",0,trial,-1,g[k]);if(!s||!s->logical_bytes||!s->events)continue;x[n]=(double)s->events/(double)s->logical_bytes;y[n]=s->elapsed*1e9/(double)s->logical_bytes;n++;}double sl,rr;linreg(x,y,n,&sl,&rr);if(good(sl)&&good(rr)){slopes[ns]=sl;fits[ns]=rr;ns++;}
    }
    double ebuf[32],sbuf[32],fbuf[32];memcpy(ebuf,effects,ne*sizeof(double));memcpy(sbuf,slopes,ns*sizeof(double));memcpy(fbuf,fits,ns*sizeof(double));double effect=median(ebuf,ne),noise=robust_mad(effects,ne),slope=median(sbuf,ns),fit=median(fbuf,ns);double v64=group_median(r,"copy_turnaround",0,-1,64,0),v64k=group_median(r,"copy_turnaround",0,-1,65536,0);
    d->effect_pct=good(effect)?effect:0;d->noise_pct=good(noise)?noise:0;d->fit=good(fit)?fit:0;d->estimate_ns=good(slope)?slope:0;
    double sig=(good(effect)&&good(noise))?effect/dmax(noise,.25):0;d->score=(good(effect)&&effect>0&&good(fit)&&fit>.55)?clamp100(effect*7.0*fit*dmin(sig/3.0,1.25)):0;double threshold=dmax(1.0,good(noise)?3.0*noise:1.0);
    bool high=good(effect)&&effect>threshold&&good(fit)&&fit>=.85&&good(slope)&&slope>0;bool med=good(effect)&&effect>dmax(.75,good(noise)?2.0*noise:.75)&&good(fit)&&fit>=.65&&good(slope)&&slope>0;
    if(high)fmt(d->status,sizeof(d->status),d->score>=45?"priority":"watch");else if(med)fmt(d->status,sizeof(d->status),"watch");else fmt(d->status,sizeof(d->status),"no_evidence");if(high&&effect>5*dmax(good(noise)?noise:.01,.01))fmt(d->confidence,sizeof(d->confidence),"high");else if(med)fmt(d->confidence,sizeof(d->confidence),"medium");
    const char* keys[]={"tRDWR","tWRRD","tWTRS","tWTRL"};char pv[192];profile_values(r,pv,sizeof(pv),keys,4);
    fmt(d->evidence,sizeof(d->evidence),"固定50/50读写量，只改变切换间距：64B %.2f GB/s，64KiB %.2f GB/s；配对效应 %.2f%%，MAD %.2f%%，回归 %.3f ns/transition，R² %.3f。当前声明值：%s。",v64,v64k,good(effect)?effect:0,good(noise)?noise:0,good(slope)?slope:0,good(fit)?fit:0,pv);
    fmt(d->limitation,sizeof(d->limitation),"该测试能确认Copy相关读写转向路径是否昂贵，但CPU乱序、store buffer与IMC请求重排意味着它不能仅凭一次固定配置唯一拆出tRDWR、tWRRD、tWTRS或tWTRL中的某一个。");
}
static void copy_side_diags(Report* r){
    int nt=r->opt.threads;double rd=group_median(r,"copy_baseline","read",nt,0,0),wr=group_median(r,"copy_baseline","write_nt",nt,0,0),cp=group_median(r,"copy_baseline","copy_nt",nt,0,0);double payload=cp>0?cp/2.0:BAD_VALUE;
    double ur=(rd>0&&good(payload))?payload/rd:BAD_VALUE,uw=(wr>0&&good(payload))?payload/wr:BAD_VALUE;
    Diagnostic* w=add_diag(r,"copy_write_path","Copy短板：写入数据路径","tWRWRSCL / tWRWRSC-SD-DD / tCWL / write-side IMC");if(w){double dom=(good(uw)&&good(ur))?uw-ur:BAD_VALUE;w->effect_pct=good(dom)?100*dom:0;w->score=good(dom)&&dom>0?clamp100(dom*180.0*dmin(good(uw)?uw:0,1.0)):0;bool pri=good(dom)&&dom>.18&&uw>.68,watch=good(dom)&&dom>.09&&uw>.55;if(pri){fmt(w->status,sizeof(w->status),"priority");fmt(w->confidence,sizeof(w->confidence),"medium");}else if(watch){fmt(w->status,sizeof(w->status),"watch");fmt(w->confidence,sizeof(w->confidence),"medium");}else {fmt(w->status,sizeof(w->status),"no_evidence");fmt(w->confidence,sizeof(w->confidence),"medium");w->score=0;}const char* keys[]={"tWRWRSCL","tWRWRSC","tWRWRSD","tWRWRDD","tCWL","tRCDWR","tWR"};char pv[256];profile_values(r,pv,sizeof(pv),keys,7);fmt(w->evidence,sizeof(w->evidence),"%d线程独立Read %.2f GB/s，Write-NT %.2f GB/s，Copy %.2f GB/s（有效复制 %.2f GB/s）。Copy每个方向占独立Read %.1f%%、独立Write %.1f%%；写侧相对压力高 %.1f 个百分点。声明值：%s。",nt,rd,wr,cp,payload,good(ur)?ur*100:0,good(uw)?uw*100:0,good(dom)?dom*100:0,pv);fmt(w->limitation,sizeof(w->limitation),"独立Read/Write不是并发Copy的严格物理上限，因此这里定位的是写侧路径压力而非某一条时序的因果贡献；需要后续Bank/命令级证据或A/B才能单项定责。");}
    Diagnostic* q=add_diag(r,"copy_read_path","Copy短板：读取数据路径","tRDRDSCL / tRDRDSC-SD-DD / read-side IMC");if(q){double dom=(good(ur)&&good(uw))?ur-uw:BAD_VALUE;q->effect_pct=good(dom)?100*dom:0;q->score=good(dom)&&dom>0?clamp100(dom*180.0*dmin(good(ur)?ur:0,1.0)):0;bool pri=good(dom)&&dom>.18&&ur>.68,watch=good(dom)&&dom>.09&&ur>.55;if(pri){fmt(q->status,sizeof(q->status),"priority");fmt(q->confidence,sizeof(q->confidence),"medium");}else if(watch){fmt(q->status,sizeof(q->status),"watch");fmt(q->confidence,sizeof(q->confidence),"medium");}else {fmt(q->status,sizeof(q->status),"no_evidence");fmt(q->confidence,sizeof(q->confidence),"medium");q->score=0;}const char* keys[]={"tRDRDSCL","tRDRDSC","tRDRDSD","tRDRDDD","tRCDRD","tCL"};char pv[256];profile_values(r,pv,sizeof(pv),keys,6);fmt(q->evidence,sizeof(q->evidence),"%d线程独立Read %.2f GB/s，Write-NT %.2f GB/s，Copy %.2f GB/s（有效复制 %.2f GB/s）。Copy每个方向占独立Read %.1f%%、独立Write %.1f%%；读侧相对压力高 %.1f 个百分点。声明值：%s。",nt,rd,wr,cp,payload,good(ur)?ur*100:0,good(uw)?uw*100:0,good(dom)?dom*100:0,pv);fmt(q->limitation,sizeof(q->limitation),"该指标只能判断读取数据路径是否比写侧更接近其独立能力边界，不能由此把损失直接归因给tRDRDSCL、tRCDRD或tCL中的某一个。");}
}
static void copy_scaling_diag(Report* r){
    Diagnostic* d=add_diag(r,"copy_scaling","Copy线程扩展/全局数据路径","MCLK / UCLK / FCLK / IMC / channel bandwidth (context)");if(!d)return;double one=group_median(r,"copy_baseline","copy_nt",1,0,0),best=0;int bt=0;for(int t=1;t<=r->opt.threads;t++){double x=group_median(r,"copy_baseline","copy_nt",t,0,0);if(good(x)&&x>best){best=x;bt=t;}}double scale=(one>0&&best>0)?best/one:BAD_VALUE;d->effect_pct=good(scale)?100*(scale-1):0;d->score=0;fmt(d->status,sizeof(d->status),"observed");fmt(d->confidence,sizeof(d->confidence),"high");fmt(d->evidence,sizeof(d->evidence),"1线程Copy %.2f GB/s；最高已测 %d线程 %.2f GB/s；扩展倍率 %.3f×。",one,bt,best,good(scale)?scale:0);fmt(d->limitation,sizeof(d->limitation),"线程扩展用于识别是否很早触及全局数据路径上限。饱和本身不是时序设置错误，因此不参与具体时序优先级排名。");
}
static void copy_loaded_diag(Report* r){
    Diagnostic* d=add_diag(r,"copy_queue_pressure","Copy负载下IMC排队/转向压力","IMC scheduling / turnaround / UCLK-FCLK path (combined)");if(!d)return;int bg=r->opt.threads>1?r->opt.threads-1:0;double idle=group_median(r,"loaded_latency","idle",0,0,0),copy=group_median(r,"loaded_latency","copy_load",bg,0,0),read=group_median(r,"loaded_latency","read_load",bg,0,0),cbg=group_median(r,"loaded_latency","copy_load",bg,0,1),rbg=group_median(r,"loaded_latency","read_load",bg,0,1);double extra=(copy>0&&read>0)?100*(copy/read-1):BAD_VALUE;d->effect_pct=good(extra)?extra:0;d->score=0;fmt(d->status,sizeof(d->status),"observed");fmt(d->confidence,sizeof(d->confidence),"high");fmt(d->evidence,sizeof(d->evidence),"空载随机延迟 %.2f ns；%d线程纯读 %.2f ns @ %.2f GB/s；同线程Copy背景 %.2f ns @ %.2f logical GB/s；Copy相对纯读延迟差 %.1f%%。",idle,bg,read,rbg,copy,cbg,good(extra)?extra:0);fmt(d->limitation,sizeof(d->limitation),"Copy背景同时改变读写比例、流量组成与排队，不能单独识别具体时序；它只用于交叉验证turnaround/控制器压力是否真实存在。");
}
static void copy_tail_diag(Report* r){
    Diagnostic* d=add_diag(r,"copy_tail","Copy负载下短窗口尾延迟","tRFC/tREFI/Refresh Mode or IMC queueing (unresolved)");if(!d)return;int bg=r->opt.threads>1?r->opt.threads-1:0;double i50=group_median(r,"copy_stall_probe","idle_short_window",-1,0,2),i99=group_median(r,"copy_stall_probe","idle_short_window",-1,0,3),c50=group_median(r,"copy_stall_probe","copy_load_short_window",bg,0,2),c99=group_median(r,"copy_stall_probe","copy_load_short_window",bg,0,3),c999=group_median(r,"copy_stall_probe","copy_load_short_window",bg,0,4);double amp=(i50>0&&i99>0&&c50>0&&c99>0)?100*((c99/c50)/(i99/i50)-1):BAD_VALUE;d->effect_pct=good(amp)?amp:0;d->score=0;fmt(d->status,sizeof(d->status),"unresolved");fmt(d->confidence,sizeof(d->confidence),"low");fmt(d->evidence,sizeof(d->evidence),"空载短窗口 P50/P99 %.2f/%.2f ns；Copy负载 P50/P99/P99.9 %.2f/%.2f/%.2f ns；归一化尾部放大 %.1f%%。",i50,i99,c50,c99,c999,good(amp)?amp:0);fmt(d->limitation,sizeof(d->limitation),"没有Refresh事件计数器和周期相关性，不能把尾部放大自动归因给tRFC/tREFI；Copy排队、OS中断和其他stall也会进入尾部，因此本项不参与参数排名。");
}
static void copy_parallel_proxy(Report* r){
    Diagnostic* d=add_diag(r,"copy_bank_parallel_proxy","Bank/ACT并行候选路径","tRRDS / tRRDL / tFAW / SCL (需要Bank映射)");if(!d)return;double a=group_median(r,"copy_path_proxy","random_latency",-1,0,0),b=group_median(r,"copy_path_proxy","parallel_8_chains",-1,0,0);double eff=(a>0&&b>0)?100.0*(a/b)/8.0:BAD_VALUE;d->effect_pct=good(eff)?100-eff:0;d->score=0;fmt(d->status,sizeof(d->status),"unresolved");fmt(d->confidence,sizeof(d->confidence),"low");fmt(d->evidence,sizeof(d->evidence),"单依赖链 %.2f ns/access；8独立链 %.2f ns/access；相对理想8×并发效率 %.1f%%。",a,b,good(eff)?eff:0);fmt(d->limitation,sizeof(d->limitation),"没有物理地址到Bank/BankGroup映射时，独立链不能证明ACT落在哪些Bank，因此不能把并发效率直接变成tRRDS/tRRDL/tFAW的Copy损失估计。");
}
static void copy_row_proxy(Report* r){
    Diagnostic* d=add_diag(r,"copy_row_proxy","Row conflict候选路径","tRP / tRCDRD / tRC / tRAS (需要Bank/Row映射)");if(!d)return;double a=group_median(r,"copy_path_proxy","random_latency",-1,0,0),b=group_median(r,"copy_path_proxy","page_local_latency",-1,0,0);d->effect_pct=(a>0&&b>0)?100*(a/b-1):0;d->score=0;fmt(d->status,sizeof(d->status),"unresolved");fmt(d->confidence,sizeof(d->confidence),"low");fmt(d->evidence,sizeof(d->evidence),"全范围随机 %.2f ns；页内随机 %.2f ns；观测差 %.2f ns。",a,b,a-b);fmt(d->limitation,sizeof(d->limitation),"虚拟页局部性同时改变TLB、预取和可能的DRAM行命中；没有Bank/Row映射不能构造same-row与same-bank-different-row正交对照，因此不参与Copy参数排名。");
}
static void copy_cached_diag(Report* r){
    Diagnostic* d=add_diag(r,"copy_store_policy","Copy写策略敏感度","CPU cache/store policy (not BIOS timing ranking)");if(!d)return;int nt=r->opt.threads;double ntc=group_median(r,"copy_baseline","copy_nt",nt,0,0),cc=group_median(r,"copy_baseline","copy_cached",nt,0,0);double e=(ntc>0&&cc>0)?100*(ntc/cc-1):BAD_VALUE;d->effect_pct=good(e)?e:0;d->score=0;fmt(d->status,sizeof(d->status),"observed");fmt(d->confidence,sizeof(d->confidence),"high");fmt(d->evidence,sizeof(d->evidence),"%d线程Copy-NT %.2f GB/s；Cached Copy %.2f GB/s；NT相对差异 %.1f%%。",nt,ntc,cc,good(e)?e:0);fmt(d->limitation,sizeof(d->limitation),"Cached/NT差异主要反映cache/RFO/store策略，不作为内存时序短板排名依据。");
}
static int status_weight(const char* s){if(!strcmp(s,"priority"))return 4;if(!strcmp(s,"watch"))return 3;if(!strcmp(s,"no_evidence"))return 2;if(!strcmp(s,"observed"))return 1;return 0;}
static void sort_diags(Report* r){for(size_t i=0;i<r->ndiagnostics;i++)for(size_t j=i+1;j<r->ndiagnostics;j++){Diagnostic* a=&r->diagnostics[i],*b=&r->diagnostics[j];int wa=status_weight(a->status),wb=status_weight(b->status);bool swap=wb>wa||(wb==wa&&b->score>a->score);if(swap){Diagnostic t=*a;*a=*b;*b=t;}}}
void diagnostics_build(Report* r){r->ndiagnostics=0;if(!r->complete||r->opt.smoke||!r->sufficient_memory||r->integrity_errors)return;copy_turnaround_diag(r);copy_side_diags(r);copy_loaded_diag(r);copy_scaling_diag(r);copy_cached_diag(r);copy_parallel_proxy(r);copy_row_proxy(r);copy_tail_diag(r);sort_diags(r);}
